# Generated by Django 5.0.4 on 2024-04-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlab', '0003_rename_name_candidate_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_baseUser',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('base', 'Base User'), ('admin', 'Admin')], default='ere', max_length=10),
            preserve_default=False,
        ),
    ]
